sudo: required
dist: trusty
language: cpp

cache:
  ccache: true
  directories:
    - cmake-3.4.3-Linux-x86_64/bin
    - cmake-3.4.3-Linux-x86_64/plugins
    - cmake-3.4.3-Linux-x86_64/share

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: MATRIX_EVAL="COMPILER=g++-6 && CC=gcc-6 && CXX=g++-6"
      os:
        - linux
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: MATRIX_EVAL="COMPILER=g++-4.9 && CC=gcc-4.9 && CXX=g++-4.9"
      os:
        - linux
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: MATRIX_EVAL="COMPILER=clang++-3.6
      os:
        - linux

branches:
  except:
    - gh-pages


before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./scripts/install-ci-dependencies.sh

script:
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ../cmake-3.4.3-Linux-x86_64/bin/cmake .. -DBUILD_SHARED_LIBS=ON ;fi
  - make
  - ctest --verbose

notifications:
    email: false
