sudo: required
dist: trusty
language: cpp

cache:
  ccache: true
  directories:
    - cmake-3.4.3-Linux-x86_64/bin
    - cmake-3.4.3-Linux-x86_64/plugins
    - cmake-3.4.3-Linux-x86_64/share

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
            - libboost-program-options-dev
            - libboost-test-dev
            - libboost-filesystem-dev
            - libboost-date-time-dev
      env: COMPILER=g++-6
      os:
        - linux
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libboost-program-options-dev
            - libboost-test-dev
            - libboost-filesystem-dev
            - libboost-date-time-dev
      env: COMPILER=clang++-3.8
      os:
        - linux

branches:
  except:
    - gh-pages

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CC" == "gcc" ]; then export CC="gcc-6"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" == "g++" ]; then export CXX="g++-6"; fi
  - echo "*** build libzmq"
  - git clone git://github.com/zeromq/libzmq.git
  - ( cd libzmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
  - echo "*** built zmq successfully"
  - pwd
  - ls
  - if [[ ! -f "cmake-3.4.3-Linux-x86_64/bin/cmake" ]]; then wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz && tar -xvf cmake-3.4.3-Linux-x86_64.tar.gz; fi

script:
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ../cmake-3.4.3-Linux-x86_64/bin/cmake .. ;fi
  - make

notifications:
    email: false
