sudo: required

# Use Linux unless specified otherwise
os: linux
dist: trusty
language: cpp

cache:
  ccache: true
  directories:
    - cmake-3.4.3-Linux-x86_64/bin
    - cmake-3.4.3-Linux-x86_64/plugins
    - cmake-3.4.3-Linux-x86_64/share
    - cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin
    - cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/Frameworks
    - cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/MacOS
    - cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/share
    - dependencies

matrix:
  include:

    ##########################################################################
    # Clang on OSX
    # Travis seems to take longer to start OSX instances,
    # so leave this first for the overall build to be faster
    ##########################################################################

    # XCode 6.4, OS X 10.10
    - env: MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"
      os: osx
      osx_image: xcode6.4
      compiler: clang

    # XCode 7.3, OS X 10.11
    - env: MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"
      os: osx
      osx_image: xcode7.3
      compiler: clang

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: MATRIX_EVAL="COMPILER=g++-6 && CC=gcc-6 && CXX=g++-6"
      os:
        - linux

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: MATRIX_EVAL="COMPILER=g++-4.9 && CC=gcc-4.9 && CXX=g++-4.9"
      os:
        - linux

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: MATRIX_EVAL="COMPILER=clang++-3.6
      os:
        - linux

branches:
  except:
    - gh-pages


before_install:
  - eval "${MATRIX_EVAL}"

install:
  - source scripts/install-ci-dependencies.sh

script:
  - mkdir build && cd build
  - cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_HELICS_EXAMPLES=ON -DZMQ_INSTALL_PATH=./dependencies -DBOOST_ROOT=./dependencies
  - make
#  - ctest --verbose

notifications:
    email: false
